## Needed packages for network analysis ##

        library(tidyverse)
        library(corrplot)
        library(Hmisc)
        library(psych)
        library(PerformanceAnalytics)
        library(combinat)
        library(RColorBrewer)
        library(colorRamps)
        library(colorspace)
        library(xlsx)
        library(readxl)
        library(extrafont) #use font_import() before using new fonts (takes 15min)
        library(igraph)
        library(ggplot2)
        library(scales)
        library(ggpubr)
        library(pdftools)
        library(Cairo)
        library(cairoDevice)
        library(brainGraph)
        library(RGtk2)
        library(ggstance)
        library(brainGraph)
        library(CINNA)
        library(foreach)
        library(doParallel)
        library(factoextra)